### ISSUE TITLE
Add slide transitions for navigation

### ISSUE THREAD

**Issue by viveknigam3003** [viveknigam3003/resuminator-landing#6]
## Motivation
The website supports navigation to sections on the page (like `#features`) but there are no transitions which makes the experience too jittery and abrupt. Improving this shall be a good addition towards a better user experience on the website during navigation

![ISSUE_click_jump](https://user-images.githubusercontent.com/30192068/97882241-66d53900-1d49-11eb-9686-0385ca7f5b54.gif)

## Modification
Add transitions for navigating to sections on the page to make the navigation smooth using any CSS Transition library or Animation Library for React.

**Comment by cgaswin** [comment]
Will using scroll:smooth in css fix this issue?

**Comment by viveknigam3003** [comment]
This issue should be marked stale now I believe. Cause the website is completely revamped now 😄

**Comment by viveknigam3003** [comment]
@AswinCG2002 I was talking about smoothly scrolling to the section when clicking on the menu bar option. I'm not sure if just adding `scroll:smooth` would achieve this. Anyways, I'll close this issue now, and open a new one later for the latest website.
